### ISSUE TITLE
Some Links Have Wrong Hyperlinks

### ISSUE THREAD

**Issue by marshalmiller** [rottingresearch/rottingresearch#217]
When the analysis runs and displays the results, some of the hyperlinks on the list of URLs have "rottingresearch.org" appended to the front of the URL. It does not appear on every link. I have not figured out the pattern.

**Comment by anshikjain18** [comment]
Hi @marshalmiller, I have raised a pull request with the fix [here](https://github.com/rottingresearch/rottingresearch/pull/219).

It was happening because some URLs do not have a scheme with them (for ex - ons.org/licenses/BY-NC-ND/4.0/) that are appended to the machine hostname by default by the browser.

In my fix, I am checking for those specific URLs and appending them to a 'http://' scheme as not all webpages are 'https://'.

Let me know if there are any further corrections required in this context.

**Comment by marshalmiller** [comment]
@anshikjain18 Thank you for your help. I will run a few tests and merge it once I am done. Thanks!

**Comment by marshalmiller** [comment]
Resolved in PR #219
