### ISSUE TITLE
rottingresearch.org is down(?)

### ISSUE THREAD

**Issue by sommer-gei** [rottingresearch/rottingresearch#295]
Hey!

ATM it seems that your (main) website at domain `rottingresearch.org` is _down_/not available. :/

I get (after some time) the `Error code 524` from Cloudflare and https://downforeveryoneorjustme.com/rottingresearch.org?proto=https ([archive.is](https://archive.is/wip/Tl7uo)) also says the domain is down.

FYI: Your [Uptime Kuma](https://status.rottingresearch.org/status/rr) ([archive.is](https://archive.is/wip/4PoB1)) says everything is fine/100% up.

Thanks in advance + BR!

**Comment by marshalmiller** [comment]
@sommer-gei Thank you for bringing this to our attention. It turns out that it was a DNS issue (always is). The Uptime instance is connected via the Docker Socket, so it so the docker container as running and was not testing public accessibility. This is an issue that I will adjust and resolve so that it more properly monitors the status. The site should be live now. Please let us know if you have any further issues.
